apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: lunch-api
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http